"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

<<<<<<< .mine
import os.path 
import sae.const
from os import environ
debug = not environ.get("wodecangshu", "") 
if debug:
#LOCAL ±¾µØµ÷ÊÔÓÃ£¬±ãÓÚµ¼³öÊý¾Ý¿â,¸ù¾Ý±¾µØMYSQLÊý¾Ý¿âÌîÐ´ÏÂÃæ²ÎÊý<----------------Èç¹ûÎÄ¼þÖÐ³öÏÖÖÐÎÄ£¬Ò»¶¨ÒªÔÚ¿ªÊ¼Ìí¼Ó #coding:utf-8
    #coding:utf-8 
    MYSQL_DB = 'library'    
    MYSQL_USER = 'root' 
    MYSQL_PASS = '123456' 
    MYSQL_HOST_M = '127.0.0.1' 
    MYSQL_HOST_S = '127.0.0.1' 
    MYSQL_PORT = '3306' 
else: 
#SAE 
    import sae.const 
    MYSQL_DB = sae.const.MYSQL_DB 
    MYSQL_USER = sae.const.MYSQL_USER 
    MYSQL_PASS = sae.const.MYSQL_PASS 
    MYSQL_HOST_M = sae.const.MYSQL_HOST 
    MYSQL_HOST_S = sae.const.MYSQL_HOST_S 
    MYSQL_PORT = sae.const.MYSQL_PORT
||||||| .r2
=======
import os.path 
import sae.const
from os import environ
debug = not environ.get("wodecangshu", "") 
if debug:
#LOCAL æœ¬åœ°è°ƒè¯•ç”¨ï¼Œä¾¿äºŽå¯¼å‡ºæ•°æ®åº“,æ ¹æ®æœ¬åœ°MYSQLæ•°æ®åº“å¡«å†™ä¸‹é¢å‚æ•°<----------------å¦‚æžœæ–‡ä»¶ä¸­å‡ºçŽ°ä¸­æ–‡ï¼Œä¸€å®šè¦åœ¨å¼€å§‹æ·»åŠ  #coding:utf-8
    #coding:utf-8 
    MYSQL_DB = 'library'    
    MYSQL_USER = 'root' 
    MYSQL_PASS = '19940331' 
    MYSQL_HOST_M = '127.0.0.1' 
    MYSQL_HOST_S = '127.0.0.1' 
    MYSQL_PORT = '3306' 
else: 
#SAE 
    import sae.const 
    MYSQL_DB = sae.const.MYSQL_DB 
    MYSQL_USER = sae.const.MYSQL_USER 
    MYSQL_PASS = sae.const.MYSQL_PASS 
    MYSQL_HOST_M = sae.const.MYSQL_HOST 
    MYSQL_HOST_S = sae.const.MYSQL_HOST_S 
    MYSQL_PORT = sae.const.MYSQL_PORT
>>>>>>> .r8


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j59odg2oe-&+m_58o)zs8mz(vnqw#7qtwoewp$z7jewza)y2-u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'books',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'library',    
        'USER': 'root',   
        'PASSWORD': '19940331', 
        'HOST': '', 
        'PORT': '3306', 
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
